/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import gsap from "gsap";
import { Mask, useGLTF } from "@react-three/drei";

export default function Board() {
  const { nodes } = useGLTF("/models/board.glb");
  const ref = useRef();

  console.log(nodes);

  useEffect(() => {
    gsap.to(ref.current.rotation, {
      x: 0.5,
      y: -0.2,
      duration: 1,
    });
    gsap.to(ref.current.scale, {
      x: 0.3,
      y: 0.3,
      z: 0.3,
      duration: 1,
    });
  });

  return (
    <group ref={ref} scale={[0.8, 0.8, 0.8]} rotation={[0, -2, 0]}>
      <Mask id={1}>
        <bufferGeometry {...nodes.piece.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Plane.geometry} />
      </Mask>
    </group>
  );
}

useGLTF.preload("/models/board.glb");
