/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import gsap from "gsap";
import { Mask, useGLTF } from "@react-three/drei";

export default function City() {
  const { nodes } = useGLTF("/models/city.glb");
  const ref = useRef();

  useEffect(() => {
    gsap.to(ref.current.position, { y: -0.4, z: -1.2, duration: 1 });
  });

  return (
    <group ref={ref} position={[-0.2, -1, 8]} scale={[0.3, 0.3, 0.3]}>
      <Mask id={1}>
        <bufferGeometry {...nodes.city.geometry} />
      </Mask>
      <Mask id={1} rotation={[-Math.PI / 2, 0, 0]} position={[0, 0, 0]}>
        <planeGeometry args={[30, 30]} />
      </Mask>
    </group>
  );
}

useGLTF.preload("/models/city.glb");
