/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { Mask, useGLTF } from "@react-three/drei";

export function Laptop() {
  const { nodes } = useGLTF("/models/laptop.glb");
  return (
    <group position={[0, -1.5, -1]} scale={[2, 2, 2]} rotation={[0, -0.1, 0]}>
      <Mask
        id={1}
        geometry={nodes.bezel.geometry}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <bufferGeometry {...nodes.bezel.geometry} />
      </Mask>
      <Mask
        id={1}
        geometry={nodes.base.geometry}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <bufferGeometry {...nodes.base.geometry} />
      </Mask>
      <Mask
        id={1}
        geometry={nodes.screen.geometry}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <bufferGeometry {...nodes.screen.geometry} />
      </Mask>
    </group>
  );
}

useGLTF.preload("/models/laptop.glb");

export default Laptop;
