/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useEffect, Suspense } from "react";
import gsap from "gsap";
import { Mask, Plane, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { VideoMaterial } from "../lib";

export default function Monitor({ opacityRef }) {
  const { nodes } = useGLTF("/models/acer.glb");
  const groupRef = useRef();
  const videoRef = useRef();
  const materialRef = useRef();

  useEffect(() => {
    gsap.to(groupRef.current.position, {
      y: -2.4,
      z: 0,
      duration: 1,
    });
    gsap.to(groupRef.current.rotation, { y: -Math.PI / 2, duration: 1 });
  });

  useFrame(() => {
    if (materialRef.current) materialRef.current.opacity = opacityRef.value;
  });

  return (
    <group
      ref={groupRef}
      position={[0, -20, 30]}
      rotation={[0, -Math.PI / 2, 0]}
      scale={[4.8, 4.8, 4.8]}
    >
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_44.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_41.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_42.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_37.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_38.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_39.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_7.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_8.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_49.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_51.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_46.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_47.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_5.geometry} />
      </Mask>
      <Plane
        ref={videoRef}
        position={[0.5, 0.54, 0]}
        scale={[1.6 * 0.418, 0.9 * 0.418, 1.0]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <Suspense fallback={<meshBasicMaterial transparent opacity={0} />}>
          <VideoMaterial
            url="./videos/dataVisualiser.mp4"
            opacity={0}
            ref={materialRef}
          />
        </Suspense>
      </Plane>
    </group>
  );
}

useGLTF.preload("/models/acer.glb");
