/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import gsap from "gsap";
import { Mask, useGLTF } from "@react-three/drei";

export default function Monitor() {
  const { nodes } = useGLTF("/models/acer.glb");
  const ref = useRef();

  useEffect(() => {
    gsap.to(ref.current.position, {
      y: -2.4,
      z: 0,
      duration: 1,
    });
    gsap.to(ref.current.rotation, { y: -Math.PI / 2, duration: 1 });
  });

  return (
    <group
      ref={ref}
      position={[0, -20, 30]}
      rotation={[0, -Math.PI / 2, 0]}
      scale={[4.8, 4.8, 4.8]}
    >
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_44.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_41.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_42.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_37.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_38.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_39.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_7.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_8.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_49.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_51.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_46.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_47.geometry} />
      </Mask>
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_5.geometry} />
      </Mask>
    </group>
  );
}

useGLTF.preload("/models/acer.glb");
