/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Levi (https://sketchfab.com/leviromano)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/samsung-phone-030019d343df47e598e929a785d1e749
title: Samsung Phone
*/

import React, { useRef, useEffect } from "react";
import gsap from "gsap";
import { Mask, useGLTF } from "@react-three/drei";

export function Phone() {
  const { nodes } = useGLTF("/models/phone.glb");
  const ref = useRef();

  useEffect(() => {
    gsap.to(ref.current.rotation, { x: 0, y: 0, duration: 1 });
  });

  return (
    <group
      ref={ref}
      position={[0, -0.45, 0]}
      rotation={[-Math.PI / 6, -Math.PI / 3, 0]}
    >
      <Mask id={1} scale={[0.06, 0.06, 0.06]} rotation={[Math.PI / 2, 0, 0]}>
        <bufferGeometry {...nodes["3dphoneuvmap_sides_0"].geometry} />
      </Mask>
      <Mask id={1} scale={[0.06, 0.06, 0.06]} rotation={[Math.PI / 2, 0, 0]}>
        <bufferGeometry {...nodes["3dphoneuvmap_lowerface_0"].geometry} />
      </Mask>
      <Mask id={1} scale={[0.06, 0.06, 0.06]} rotation={[Math.PI / 2, 0, 0]}>
        <bufferGeometry {...nodes["3dphoneuvmap_topface_0"].geometry} />
      </Mask>
    </group>
  );
}

useGLTF.preload("/models/phone.glb");

export default Phone;
