/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import gsap from "gsap";
import { Mask, useGLTF } from "@react-three/drei";

export default function Plane({ start, end, rotation }) {
  const { nodes } = useGLTF("/models/plane.glb");
  const ref = useRef();

  useEffect(() => {
    gsap.to(ref.current.position, {
      ...end,
      duration: 1,
    });
  });

  return (
    <group
      ref={ref}
      position={start}
      scale={[0.02, 0.02, 0.02]}
      rotation={rotation}
    >
      <Mask id={1}>
        <bufferGeometry {...nodes.body.geometry} />
      </Mask>
    </group>
  );
}

useGLTF.preload("/models/plane.glb");
