/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import gsap from "gsap";
import { Mask, useGLTF } from "@react-three/drei";

export default function User() {
  const { nodes } = useGLTF("/models/user.glb");
  const ref = useRef();

  useEffect(() => {
    gsap.to(ref.current.rotation, {
      x: 0,
      y: 0,
      duration: 1,
    });
  });

  return (
    <group
      ref={ref}
      scale={[2.5, 2.5, 2.5]}
      position={[0, -1.6, 0]}
      rotation={[0.8, 0, 0]}
    >
      <Mask id={1}>
        <bufferGeometry {...nodes.Object_2.geometry} />
      </Mask>
    </group>
  );
}

useGLTF.preload("/models/user.glb");
